export const states = [
  { id: 1, value: 'Buenos Aires' },
  { id: 2, value: 'Catamarca' },
  { id: 3, value: 'Chaco' },
  { id: 4, value: 'Chubut' },
  { id: 5, value: 'Córdoba' },
  { id: 6, value: 'Corrientes' },
  { id: 7, value: 'Entre Ríos' },
  { id: 8, value: 'Formosa' },
  { id: 9, value: 'Jujuy' },
  { id: 10, value: 'La Pampa' },
  { id: 11, value: 'La Rioja' },
  { id: 12, value: 'Mendoza' },
  { id: 13, value: 'Misiones' },
  { id: 14, value: 'Neuquén' },
  { id: 15, value: 'Río Negro' },
  { id: 16, value: 'Salta' },
  { id: 17, value: 'San Juan' },
  { id: 18, value: 'San Luis' },
  { id: 19, value: 'Santa Cruz' },
  { id: 20, value: 'Santa Fe' },
  { id: 21, value: 'Santiago del Estero' },
  { id: 22, value: 'Tierra del Fuego' },
  { id: 23, value: 'Tucumán' }
]