import { initialInventory } from './seedInventory'
import { initialPrice } from './seedPrice'
import { Product } from '../interface/product'
import { Price } from '../interface/price'
import { Inventory } from '../interface/inventory'

const getInventory = (productId: string): Inventory => {
  return initialInventory.find(p => p.product_id === productId) ?? {
    product_id: productId,
    stock: 0,
    isActive: true
  }
}

const getPrice = (productId: string): Price => {
  return initialPrice.find(p => p.product_id === productId) ?? {
    price: 0,
    iva: 0,
    outstanding: false,
    product_id: productId
  }
}

interface SeedData {
  products: Product[];
}

export const initialData: SeedData = {
  products: [
    {
      supplierId: '5912',
      supplier: '1',
      title: 'Panel solar 585W - bifacial Astro N5 - Tier 1',
      description: '14.36A (Isc) | 51.50V (Voc) | 144 medias celdas | Monocristalino Half Cell',
      specification: {
        dimensiones: '2278x1134x30',
        peso: '32.1',
        tipo_Celda: 'monocristalino',
        potencia_nominal: '585',
        voltaje_nominal: '43.27',
        corriente_nominal: '13.52',
        voltaje_circuito_abierto: '51.50',
        corriente_cortocircuito: '14.36',
        eficiencia_modulo: '22.6'
      },
      brand: 'Astronergy',
      model: 'Astro N5',
      origin: 'China',
      images: ['ps-bi-astro.webp', 'ps-bi-astro-585W_1.webp', 'ps-bi-astro-585W_2.webp'],
      stock: getInventory('5912'),
      price: getPrice('5912'),
      warranty: '30 años de garantía de potencia lineal, 15 años de garantía de producto',
      slug: 'panel-solar-585wp-astronergy-5912',
      category: 1,
      system: 6,
      subCategory: 1,
      tags: ['solar', 'panel', 'policristalino', '585W', 'astronergy', 'astro N5', 'high-efficiency', 'photovoltaic', 'bifacial'],
      information: 'Panel solar 585W bifacial monocristalino Astro N5 - Tier 1, 144 celdas, 5BB. Certificado por TÜV Rheinland. La serie ASTRO N5 emplea la tecnología de celdas TOPCon 4.0 tipo n de última generación, desarrollada por Astronergy, y obleas de silicio de gran tamaño de 182 mm, combinadas con tecnología SMBB. Gracias a su encapsulado de alta densidad, corte no destructivo y otros procesos avanzados, el producto mejora aún más el rendimiento y la fiabilidad de la generación de energía para satisfacer las necesidades de los clientes en cualquier escenario.',
      url: 'www.astronergy.com'
    },
    {
      supplierId: '5960',
      supplier: '1',
      title: 'Panel solar 450W - bifacial Astro N7s - Tier 1',
      description: 'Black frame | 14.35A (Isc) | 39.2 (Voc) | 108 celdas ',
      specification: {
        dimensiones: '1762x1134x30',
        peso: '21.5',
        tipo_celda: 'mono_cristalino_tipo_N',
        potencia_nominal: '450',
        voltaje_nominal: '32.94',
        corriente_nominal: '13.66',
        voltaje_circuito_abierto: '39.20',
        corriente_cortocircuito: '14.35',
        eficiencia_modulo: '22.5'
      },
      brand: 'Astronergy',
      model: 'Astro N7s',
      origin: 'China',
      images: ['ps-bi-astro-black.webp', 'ps-bi-astro-450W_1.webp', 'ps-bi-astro-450W_2.webp'],
      stock: getInventory('5960'),
      price: getPrice('5960'),
      slug: 'panel-solar-450wp-astroenrgy-5960',
      category: 1,
      system: 6,
      subCategory: 1,
      tags: ['solar', 'panel', 'monocristalino', 'Black Frame', 'Astro N7s', '450W', 'bifacial', 'high-efficiency', 'photovoltaic'],
      information: 'Panel solar 450W bifacial monocristalino Black Frame Astro N7s - Tier 1, 108 celdas, 5BB, 30 años de garantía de potencia lineal, 15 años de garantía de producto, certificado por TÜV Rheinland. Equipado con la tecnología de células solares TOPCon 4.0 de Astronergy, recientemente mejorada, que utiliza obleas de silicio rectangulares y la innovadora tecnología ZBB, el módulo completamente negro de 48 células alcanza una potencia de 460 W y una eficiencia de hasta un 23,0 %. No tiene barras colectoras, cintas tipo arpón ni puntos PAD. La incorporación de accesorios negros, como marcos, realza su estética. Su diseño elegante, con una dimensión única de <2 m² y un peso de <23 kg, facilita su instalación y manejo por una sola persona. Se adapta perfectamente a las aplicaciones residenciales, con las ventajas únicas de ser ligero, eficiente, de alta calidad y estético.',
      url: 'www.astronergy.com'
    },
    {
      supplierId: '5856',
      supplier: '1',
      title: 'Panel solar 330W policristalino Nuuko',
      description: '9.22A (Isc) | 45.5V (Voc) | 72 celdas | Policristalino',
      specification:
        {
          dimensiones: '1956x992x35',
          peso: '22',
          tipo_celda: 'policristalino',
          potencia_nominal: '330',
          voltaje_nominal: '37.8',
          corriente_nominal: '8.73',
          voltaje_circuito_abierto: '45.5',
          corriente_cortocircuito: '9.22',
          eficiencia_modulo: '17.0'
        }
      ,
      brand: 'Nuuko',
      model: 'NKP330-72P',
      origin: 'China',
      images: ['ps-pl-nuuko.webp', 'ps-pl-nuuko-330w_1.webp', 'ps-pl-nuuko-330w_2.webp'],
      stock: getInventory('5856'),
      price: getPrice('5856'),
      slug: 'panel-solar-330wp-nuuko-5856',
      category: 1,
      system: 6,
      subCategory: 1,
      tags: [
        'solar',
        'panel',
        'policristalino',
        '330W',
        'nuuko',
        'high-efficiency',
        'photovoltaic'
      ],
      information: 'Panel solar 330W policristalino Nuuko, 72 celdas, 25 años de garantía de potencia lineal, 12 años de garantía de producto. El panel solar Nuuko 330W policristalino está diseñado para ofrecer una combinación de alta eficiencia y resistencia estructural. Cuenta con un marco reforzado con tecnología de doble capa impermeable, protección contra microgrietas y PID, asegurando un rendimiento estable a largo plazo. Su capacidad de soportar condiciones extremas lo convierte en una excelente opción para proyectos residenciales y comerciales.',
      url: 'www.nuukopower.com'
    },
    {
      supplierId: '5391',
      supplier: '1',
      title: 'Panel Solar 290W AMERISOLAR AS-6P30',
      description: ' 9,59A (Isc) | 39,2V (Voc) | 60 celdas | Policristalino',
      specification: {
        dimensiones: '1640x992x35',
        peso: '17.5',
        tipo_celda: 'policristalino',
        potencia_nominal: '290',
        voltaje_nominal: '32.0',
        corriente_nominal: '9.07',
        voltaje_circuito_abierto: '39.2',
        corriente_cortocircuito: '9.59',
        eficiencia_modulo: '17.83'
      },
      brand: 'Amerisolar',
      model: 'AS-6P30',
      origin: 'China',
      images: ['ps-pl-amerisolar.webp', 'ps-pl-amerisolar-290w_1.webp', 'ps-pl-amerisolar-290w_2.webp'],
      stock: getInventory('5391'),
      price: getPrice('5391'),
      slug: 'panel-solar-290wp-amerisolar-5391',
      category: 1,
      system: 6,
      subCategory: 1,
      tags: ['solar', 'panel', 'policristalino', '290W', 'AMERISOLAR', 'AS-6P30', 'high-efficiency', 'photovoltaic'],
      information: 'Panel Solar 290W AMERISOLAR AS-6P30, policristalino, 60 celdas, 5BB, 30 años de garantía de potencia lineal, 20 años de garantía de producto. Alta eficiencia de conversión de módulos de hasta el 18,44 % gracias a la innovadora tecnología de celdas de cinco barras colectoras. Baja degradación y excelente rendimiento en condiciones de alta temperatura y baja luminosidad. Su robusta estructura de aluminio garantiza que los módulos soporten cargas de viento de hasta 3600 Pa y cargas de nieve de hasta 5400 Pa. Alta fiabilidad en condiciones ambientales extremas (superando las pruebas de niebla salina, amoníaco y granizo). Resistencia a la degradación inducida por potencial (PID).',
      url: 'www.https://www.weamerisolar.eu/es/'
    },
    {
      supplierId: '5432',
      supplier: '1',
      title: 'Panel Solar 285W AMERISOLAR AS-6P30',
      description: '9,42A (Isc) | 38,7V (Voc) | 60 celdas | Policristalino',
      specification: {
        dimensiones: '1640x992x35',
        peso: '17.5',
        tipo_celda: 'policristalino',
        potencia_nominal: '285',
        voltaje_nominal: '31.8',
        corriente_nominal: '8.97',
        voltaje_circuito_abierto: '39.0',
        corriente_cortocircuito: '9.48',
        eficiencia_modulo: '17.52'
      },
      brand: 'Amerisolar',
      model: 'AS-6P30',
      origin: 'China',
      images: ['ps-pl-amerisolar.webp', 'ps-pl-amerisolar-290w.webp_1.webp', 'ps-pl-amerisolar-290w.webp_2.webp'],
      stock: getInventory('5432'),
      price: getPrice('5432'),
      slug: 'panel-solar-285wp-amerisolar-5432',
      category: 6,
      system: 1,
      subCategory: 6,
      tags: ['solar', 'panel', 'policristalino', '285W', 'AMERISOLAR', 'AS-6P30', 'high-efficiency', 'photovoltaic'],
      information: 'Panel Solar 285W AMERISOLAR AS-6P30, policristalino, 60 celdas, 5BB, 30 años de garantía de potencia lineal, 20 años de garantía de producto. Alta eficiencia de conversión de módulos de hasta el 18,44 % gracias a la innovadora tecnología de celdas de cinco barras colectoras. Baja degradación y excelente rendimiento en condiciones de alta temperatura y baja luminosidad. Su robusta estructura de aluminio garantiza que los módulos soporten cargas de viento de hasta 3600 Pa y cargas de nieve de hasta 5400 Pa. Alta fiabilidad en condiciones ambientales extremas (superando las pruebas de niebla salina, amoníaco y granizo). Resistencia a la degradación inducida por potencial (PID).',
      url: 'www.https://www.weamerisolar.eu/es/'
    },
    {
      supplierId: '5855',
      supplier: '1',
      title: 'Panel solar 280W policristalino Nuuko',
      description: ' 9.29A (Isc) | 38.5V (Voc) | 60 celdas | Policristalino',
      specification:
        {
          dimensiones: '1640x992x35',
          peso: '19',
          tipo_celda: 'policristalino',
          potencia_nominal: '280',
          voltaje_nominal: '31.6',
          corriente_nominal: '8.86',
          voltaje_circuito_abierto: '38.5',
          corriente_cortocircuito: '9.29',
          eficiencia_modulo: '17.2'
        }
      ,
      brand: 'Nuuko',
      model: 'NKP280-60M2',
      origin: 'China',
      images: ['ps-pl-nuuko.webp', 'ps-nuuko-280w_1.webp', 'ps-nuuko-280w_2.webp'],
      stock: getInventory('5855'),
      price: getPrice('5855'),
      slug: 'panel-solar-280wp-nuuko-5855',
      category: 1,
      system: 6,
      subCategory: 1,
      tags: [
        'solar',
        'panel',
        'policristalino',
        '280W',
        'nuuko',
        'high-efficiency',
        'photovoltaic'
      ],
      information: 'Panel solar 280W policristalino Nuuko, 60 celdas, 25 años de garantía de potencia lineal, 12 años de garantía de producto. El panel solar Nuuko 280W policristalino está diseñado para ofrecer una combinación de alta eficiencia y resistencia estructural. Cuenta con un marco reforzado con tecnología de doble capa impermeable, protección contra microgrietas y PID, asegurando un rendimiento estable a largo plazo. Su capacidad de soportar condiciones extremas lo convierte en una excelente opción para proyectos residenciales y comerciales.',
      url: 'www.nuukopower.com'
    },
    {
      supplierId: '5114',
      supplier: '1',
      title: 'Batería litio monobloque Blunery',
      description: '12V | 200Ah | 2400Wh | 2000 ciclos',
      specification:
        {
          dimensiones: '218x240x522',
          peso: '22',
          voltaje_nominal_VCC: '12',
          capacidad_nominal_Wh: '2400',
          capacidad_nominal_Ah: '200',
          ciclos: '2000',
          corriente_descarga_máxima_Amps: '100',
          corriente_carga_máxima_Amps: '100',
          tecnología_cátodo: 'LFP (3,2Vpc)',
          rango_voltaje_trabajo_VCC: '10 - 14,6',
          temperatura_trabajo: '-20 - 60',
          vida_útil: '15 años',
        },
      brand: 'Blunery',
      model: 'BATBLUIND12200',
      origin: 'USA',
      images: ['bt-lt-mono-12-200-blunery.webp', 'bt-lt-mono-12-200-blunery_1.webp', 'bt-lt-mono-12-200-blunery_2.webp'],
      stock: getInventory('5114'),
      price: getPrice('5114'),
      slug: 'bateria-monobloque-12v-200ah-blunery-5114',
      category: 1,
      system: 6,
      subCategory: 3,
      tags: [
        'batería',
        'litio',
        'monobloque',
        '12V',
        '200Ah',
        '2400Wh',
        '2000 ciclos',
        'Blunery',
        'LFP',
        'high-efficiency',
        'photovoltaic'
      ],
      logo: 'bt-lt-mono-12-200-blunery.webp',
      warranty: 'El período de garantía es de 60 meses (5 años) a partir de la fecha de fabricación, indicada en el código de barras de la batería. La garantía cubre defectos de fabricación y materiales, y no cubre daños causados por el usuario.',
      information: 'La serie de baterías de iones de litio BATBLUIND12 es el reemplazo ideal de las baterías de plomo-ácido tradicionales, con tecnología LiFePO4 y BMS integrado, es una alternativa ligera y duradera a las baterías de plomo-ácido. Ofrece seguridad y buen rendimiento en temperaturas extremas, siendo ideal para energía solar, almacenamiento y respaldo de emergencia.',
      url: 'https://blunery.com/'
    },
    {
      supplierId: '4568',
      supplier: '1',
      title: 'Batería litio monobloque Blunery',
      description: '12V | 200Ah | 2400Wh | 4000 ciclos',
      specification:
        {
          dimensiones: '218x240x522',
          peso: '22',
          voltaje_nominal_VCC: '12',
          capacidad_nominal_Wh: '2400',
          capacidad_nominal_Ah: '200',
          ciclos: '4000',
          corriente_descarga_máxima_Amps: '100',
          corriente_carga_máxima_Amps: '100',
          tecnología_cátodo: 'LFP (3,2Vpc)',
          rango_voltaje_trabajo_VCC: '10 - 14,6',
          temperatura_trabajo: '-20 - 60',
          vida_útil: '15 años',
        },
      brand: 'Blunery',
      model: 'BATBLUIND12200',
      origin: 'USA',
      images: ['bt-lt-mono-12-200-blunery.webp', 'bt-lt-mono-12-200-blunery_1.webp', 'bt-lt-mono-12-200-blunery_2.webp'],
      stock: getInventory('4568'),
      price: getPrice('4568'),
      slug: 'bateria-monobloque-12v-200ah-blunery-4568',
      category: 1,
      system: 6,
      subCategory: 3,
      tags: [
        'batería',
        'litio',
        'monobloque',
        '12V',
        '200Ah',
        '2400Wh',
        '4000 ciclos',
        'Blunery',
        'LFP',
        'high-efficiency',
        'photovoltaic'
      ],
      logo: 'blunery-logo.webp',
      warranty: 'El período de garantía es de 60 meses (5 años) a partir de la fecha de fabricación, indicada en el código de barras de la batería. La garantía cubre defectos de fabricación y materiales, y no cubre daños causados por el usuario.',
      information: 'La serie de baterías de iones de litio BATBLUIND12 es el reemplazo ideal de las baterías de plomo-ácido tradicionales, con tecnología LiFePO4 y BMS integrado, es una alternativa ligera y duradera a las baterías de plomo-ácido. Ofrece seguridad y buen rendimiento en temperaturas extremas, siendo ideal para energía solar, almacenamiento y respaldo de emergencia.',
      url: 'https://blunery.com/'
    },
    {
      supplierId: '5234',
      supplier: '1',
      title: 'Batería litio rackeable Blunery',
      description: '48V | 50Ah | 2400Wh | 5000 ciclos | BMS integrado',
      specification:
        {
          dimensiones: '132x483x424',
          peso: '33',
          voltaje_nominal_VCC: '48',
          capacidad_nominal_Wh: '2400',
          capacidad_nominal_Ah: '50',
          ciclos: '5000',
          corriente_descarga_máxima_Amps: '50',
          corriente_carga_máxima_Amps: '50',
          tecnología_cátodo: 'LFP (3,2Vpc)',
          rango_voltaje_trabajo_VCC: '41 - 54',
          temperatura_trabajo: '-20 - 60',
          vida_útil: '15 años',
        },
      brand: 'Blunery',
      model: 'BATBLUTEL4850',
      origin: 'USA',
      images: ['bt-lt-rack-48v-blunery.webp', 'bt-lt-rack-48v-blunery_1.webp', 'bt-lt-rack-48v-blunery_2.webp'],
      stock: getInventory('4568'),
      price: getPrice('4568'),
      slug: 'bateria-rackeable-48v-50ah-blunery-5234',
      category: 1,
      system: 6,
      subCategory: 3,
      tags: [
        'batería',
        'litio',
        'rackeable',
        '48V',
        '50Ah',
        '2400Wh',
        '4000 ciclos',
        'Blunery',
        'LFP',
        'high-efficiency',
        'photovoltaic'
      ],
      logo: 'blunery-logo.webp',
      warranty: 'El período de garantía es de 60 meses (5 años) a partir de la fecha de fabricación, indicada en el código de barras de la batería. La garantía cubre defectos de fabricación y materiales, y no cubre daños causados por el usuario.',
      information: 'Las baterías LFP BATBLUTEL48 de BLUNERY están diseñadas para equipos de telecomunicaciones, ofreciendo mayor vida útil, menor tamaño y peso, y resistencia a entornos extremos. Son compatibles con cualquier rectificador gracias a su BMS integrado y permiten conexión en paralelo para ampliar la capacidad. Además, pueden reemplazar fácilmente las baterías de plomo-ácido VRLA sin necesidad de modificaciones adicionales. Su BMS interno proporciona protección contra sobrecarga, sobredescarga, cortocircuitos y temperaturas extremas, además de equilibrar automáticamente la carga entre celdas. Estas baterías pueden recargarse incluso en temperaturas bajo cero y ofrecen más de 5000 ciclos de carga y descarga. Su profundidad de descarga (DoD) del 100% elimina la necesidad de sobredimensionarlas. También incluyen puertos de comunicación RS232, RS485 y CAN para monitoreo y actualizaciones.',
      url: 'https://blunery.com/'
    },
    {
      supplierId: '4571',
      supplier: '1',
      title: 'Batería litio rackeable Blunery',
      description: '48V | 150Ah | 7200Wh | 5000 ciclos | BMS integrado',
      specification:
        {
          dimensiones_mm: '132x483x424',
          peso_kg: '78',
          voltaje_nominal_VCC: '48',
          capacidad_nominal_Wh: '7200',
          capacidad_nominal_Ah: '150',
          ciclos: '5000',
          corriente_descarga_máxima_Amps: '150',
          corriente_carga_máxima_Amps: '150',
          tecnología_cátodo: 'LFP (3,2Vpc)',
          rango_voltaje_trabajo_VCC: '41 - 54',
          temperatura_trabajo: '-20 - 60',
          vida_útil: '15 años',
        },
      brand: 'Blunery',
      model: 'BATBLUTEL48150',
      origin: 'USA',
      images: ['bt-lt-rack-48v-blunery.webp', 'bt-lt-rack-48v-150ah-blunery_1.webp', 'bt-lt-rack-48v-150ah-blunery_2.webp'],
      stock: getInventory('4571'),
      price: getPrice('4571'),
      slug: 'bateria-rackeable-48v-150ah-blunery-4571',
      category: 1,
      system: 6,
      subCategory: 3,
      tags: [
        'batería',
        'litio',
        'rackeable',
        '48V',
        '150Ah',
        '7200Wh',
        '5000 ciclos',
        'Blunery',
        'LFP',
        'high-efficiency',
        'photovoltaic'
      ],
      logo: 'blunery-logo.webp',
      warranty: 'El período de garantía es de 60 meses (5 años) a partir de la fecha de fabricación, indicada en el código de barras de la batería. La garantía cubre defectos de fabricación y materiales, y no cubre daños causados por el usuario.',
      information: 'Las baterías LFP BATBLUTEL48 de BLUNERY están diseñadas para equipos de telecomunicaciones, ofreciendo mayor vida útil, menor tamaño y peso, y resistencia a entornos extremos. Son compatibles con cualquier rectificador gracias a su BMS integrado y permiten conexión en paralelo para ampliar la capacidad. Además, pueden reemplazar fácilmente las baterías de plomo-ácido VRLA sin necesidad de modificaciones adicionales. Su BMS interno proporciona protección contra sobrecarga, sobredescarga, cortocircuitos y temperaturas extremas, además de equilibrar automáticamente la carga entre celdas. Estas baterías pueden recargarse incluso en temperaturas bajo cero y ofrecen más de 5000 ciclos de carga y descarga. Su profundidad de descarga (DoD) del 100% elimina la necesidad de sobredimensionarlas. También incluyen puertos de comunicación RS232, RS485 y CAN para monitoreo y actualizaciones.',
      url: 'https://blunery.com/'
    },
    {
      supplierId: '5218',
      supplier: '1',
      title: 'Batería litio rackeable HOPE 4.8L-C1 Growatt',
      description: '48V | 100Ah | 4800Wh | 3500 ciclos | BMS integrado',
      specification:
        {
          dimensiones_mm: '130x442x480',
          peso_kg: '45',
          voltaje_nominal_VCC: '48',
          capacidad_nominal_Wh: '4800',
          capacidad_nominal_Ah: '100',
          ciclos: '3500',
          corriente_descarga_máxima_Amps: '100',
          corriente_carga_máxima_Amps: '50',
          rango_voltaje_trabajo_VCC: '42 - 54',
          temperatura_trabajo: '-10 - +55',
          vida_útil: '10 años',
        },
      brand: 'Growatt',
      model: 'HOPE 4.8L-C1',
      origin: 'China',
      images: ['bt-lt-rack-48v-4800wh-growatt.webp', 'bt-lt-rack-48v-4800wh-growatt_1.webp', 'bt-lt-rack-48v-4800wh-growatt_2.webp'],
      stock: getInventory('5218'),
      price: getPrice('5218'),
      slug: 'bateria-rackeable-48v-100ah-4800wh-growatt-5218',
      category: 1,
      system: 6,
      subCategory: 3,
      tags: [
        'batería',
        'litio',
        'rackeable',
        '48V',
        '100Ah',
        '4800Wh',
        '3500 ciclos',
        'Growatt',
        'HOPE 4.8L-C1',
        'photovoltaic'
      ],
      logo: 'growatt-logo.webp',
      warranty: 'La garantía de las baterías HOPE Series de Growatt es de 5 años o hasta que se alcance la capacidad de descarga acumulada indicada en la tabla. Hope 4.8L-C1: 5 años o 9.7 MWh de capacidad de descarga acumulada.',
      information: 'La batería de litio Growatt Hope 4.8L-C1 es un dispositivo de almacenamiento de energía con terminales de potencia y señal, compuesto por celdas, componentes mecánicos, un sistema de gestión de baterías (BMS) y otros componentes.El kit y la batería se venden por separado. Fácil instalación y tamaño compact. Alta eficiencia y densidad energética. DoD de hasta el 93 %. Excelente seguridad para baterías LiFePO4.',
      url: 'https://en.growatt.com/'
    },
    {
      supplierId: '5861',
      supplier: '1',
      title: 'Batería litio rackeable HOPE 5.5L-A1 Growatt',
      description: '51.2V | 100Ah | 5500Wh | 6000 ciclos | BMS integrado',
      specification:
        {
          dimensiones_mm: '130.5x440x540',
          peso_kg: '45',
          voltaje_nominal_VCC: '51.2',
          capacidad_nominal_Wh: '5500',
          capacidad_nominal_Ah: '100',
          ciclos: '6000',
          corriente_descarga_máxima_Amps: '120',
          corriente_carga_máxima_Amps: '100',
          rango_voltaje_trabajo_VCC: '40 - 58.4',
          temperatura_trabajo: '-20 - +55',
          vida_útil: '10 años',
        },
      brand: 'Growatt',
      model: 'HOPE 5.5L-A1',
      origin: 'China',
      images: ['bt-lt-rack-48v-5500Wh-growatt.webp', 'bt-lt-rack-48v-5500Wh-growatt_1.webp', 'bt-lt-rack-48v-5500Wh-growatt_2.webp'],
      stock: getInventory('5861'),
      price: getPrice('5861'),
      slug: 'bateria-rackeable-48v-100ah-5500Wh-growatt-5861',
      category: 1,
      system: 6,
      subCategory: 3,
      tags: [
        'batería',
        'litio',
        'rackeable',
        '48V',
        '100Ah',
        '5500Wh',
        '6000 ciclos',
        'Growatt',
        'HOPE 5.5L-A1',
        'photovoltaic'
      ],
      logo: 'growatt-logo.webp',
      warranty: 'La garantía de las baterías HOPE Series de Growatt es de 5 años o hasta que se alcance la capacidad de descarga acumulada indicada en la tabla. Hope 4.8L-C1: 5 años o 9.7 MWh de capacidad de descarga acumulada.',
      information: 'La batería de litio HOPE 5.5L-A1 de Growatt, con tecnología LiFePo4, ofrece una capacidad de 5.5 kWh y un voltaje de 51.2V (106Ah), ideal para sistemas de almacenamiento de energía en aplicaciones solares. Con hasta un 93% de profundidad de descarga (DOD) y una vida útil de 6000 ciclos a 25°C (0.2C), garantiza rendimiento y durabilidad. Además, su diseño compacto y ligero facilita la instalación y el transporte. La batería cuenta con un sistema de gestión de baterías (BMS) integrado que protege contra sobrecarga, sobredescarga, sobrecorriente y sobrecalentamiento, asegurando un funcionamiento seguro y fiable.',
      url: 'https://en.growatt.com/'
    },
    {
      supplierId: '5219',
      supplier: '1',
      title: 'KIT accesorios para batería Growatt HOPE 4.8L-C1',
      description: 'brackets | tornillos | cables de potencia y cables de comunicación',
      specification:
        {
          dimensiones_mm: '130.5x440x540',
          peso_kg: '45',
          voltaje_nominal_VCC: '51.2',
          capacidad_nominal_Wh: '5500',
          capacidad_nominal_Ah: '100',
          ciclos: '6000',
          corriente_descarga_máxima_Amps: '120',
          corriente_carga_máxima_Amps: '100',
          rango_voltaje_trabajo_VCC: '40 - 58.4',
          temperatura_trabajo: '-20 - +55',
          vida_útil: '10 años',
        },
      brand: 'Growatt',
      model: 'KIT HOPE 4.8L-C1',
      origin: 'China',
      images: ['acc-hope-4.8l-c1-growatt.webp'],
      stock: getInventory('5219'),
      price: getPrice('5219'),
      slug: 'accesorio-kit-4.8l-c1-growatt-5219',
      category: 1,
      system: 6,
      subCategory: 6,
      tags: [
        'batería',
        'litio',
        'rackeable',
        'accesorios',
        'instalación',
        '48V',
        '100Ah',
        '4800Wh',
        '3500 ciclos',
        'Growatt',
        'HOPE 4.8L-L1',
        'photovoltaic'
      ],
      logo: 'growatt-logo.webp',
      information: 'El kit de accesorios para baterías Growatt HOPE 4.8L-C1 incluye soportes, tornillos, cables de potencia y cables de comunicación, necesarios para la instalación y conexión de la batería de litio HOPE 4.8L-C1 de Growatt. Los soportes y tornillos permiten fijar la batería en la posición deseada, mientras que los cables de potencia y comunicación facilitan la conexión de la batería al sistema de almacenamiento de energía y a otros dispositivos. Este kit de accesorios garantiza una instalación segura y eficiente de la batería, asegurando un rendimiento óptimo y una larga vida útil.',
      url: 'https://en.growatt.com/'
    }
  ]
}
